def yamlInput
def approval
def secretPath
def skip
pipeline{
agent any
stages{
    stage('read yaml'){
        steps{
            script {
            yamlInput = readYaml file: "${WORKSPACE}/input.yaml"
            }
    }
    }
    stage('Deployment'){
        steps{
            script{
                if (env.BRANCH_NAME == 'develop'){
                    print("This is develop branch")
                }
            }
        }
    }
}
}